# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Keep fastlane pinned through Gemfile.lock so CI runs are reproducible.

default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :tests do

    run_tests(
      scheme: "Scout",
      clean: true,
      devices: ["iPhone 17 Pro"],
      force_quit_simulator: true,
      reset_simulator: true,
      disable_concurrent_testing: true,
      max_concurrent_simulators: 1
    )

  end
end
